### ISSUE TITLE
Create and test backend using Spleeter and fastAPI

### ISSUE THREAD

**Issue by dxv2k** [dxv2k/EndtoEnd-Splitter#1]
Test Flask and fastAPI 

[fastAPI doc](https://fastapi.tiangolo.com/)
[flaskAPI doc](https://github.com/flask-api/flask-api)

[Sample structure](https://medium.com/@8B_EC/tutorial-serving-machine-learning-models-with-fastapi-in-python-c1a27319c459)
![image](https://user-images.githubusercontent.com/9569076/113504104-17956d80-9560-11eb-98e7-7d97a98d6c00.png)

**Comment by dxv2k** [comment]
![image](https://user-images.githubusercontent.com/9569076/113437522-f6723700-9410-11eb-9276-df654cbff3c5.png)
Wrapt around of what need to do

**Comment by VinhDevNguyen** [comment]
https://viblo.asia/p/huong-dan-co-ban-framework-fastapi-tu-a-z-phan-1-V3m5W0oyKO7

**Comment by dxv2k** [comment]
https://fastapi.tiangolo.com/tutorial/request-files/
File request, I'm going to test it in the morning
