### ISSUE TITLE
[BUG] spleeter.SpleeterError: ffmpeg binary not found

### ISSUE THREAD

**Issue by xXHellgate25Xx** [dxv2k/EndtoEnd-Splitter#2]

**Comment by xXHellgate25Xx** [comment]
How to install ffmepg: http://blog.gregzaal.com/how-to-install-ffmpeg-on-windows/

**Comment by dxv2k** [comment]
Using conda and run this:
`conda install -c conda-forge ffmpeg libsndfile`

**Comment by VinhDevNguyen** [comment]
> Using conda and run this:
> `conda install -c conda-forge ffmpeg libsndfile`

These library are already install with `Spleeter`, but you need to install FFmpeg build from [here](https://github.com/BtbN/FFmpeg-Builds/releases) and add to system path. Otherwise, you will get this error: 
```
raise SpleeterError("{} binary not found".format(binary))
spleeter.SpleeterError: ffmpeg binary not found
```
